---
 path_to_public_data: "/home/david/Desktop/data/lr_model.sav"
 type_of_data: "model"
 path_to_private_data: "/home/david/Desktop/spdz/Player-Data/Input-P0-0"
 path_to_this_repo: "/home/david/Desktop/fspdz"
 path_to_top_of_mpspdz: "/home/david/Desktop/spdz"
 compile: "False"
 model_type: "lr"
 metrics: "1,2,3"