---
 path_to_public_data: "/home/david/Desktop/fspdz/data/lr_model.sav"
 type_of_data: "model"
 model_holders_ip: "127.0.0.1"
 model_holders_port: "6001"
 path_to_private_data: "/home/david/Desktop/spdz/Player-Data/Input-P0-0"
 path_to_this_repo: "/home/david/Desktop/fspdz"
 path_to_top_of_mpspdz: "/home/david/Desktop/spdz"
 compile: "false"
 model_type: "lr"
 metrics: "1,2,3"
 num_of_parties: "2"
 party: "0"
 compiler: "-R 64 -Y run"
 VM: "semi2k-party.x -N 2 -p 0 run"
 protected_col: "47"
 protected_values: "[0,1]"
 online: "false"