---
 path_to_public_data: "/home/david/Desktop/fspdz/data"
 type_of_data: "audit"
 path_to_private_data: "/home/david/Desktop/spdz/Player-Data/Input-P1-0"
 path_to_this_repo: "/home/david/Desktop/fspdz"
 path_to_top_of_mpspdz: "/home/david/Desktop/spdz"
 compile: "true"
 model_type: "lr"
 metrics: "1,2,3"
 party: "1"