---
 path_to_public_data: "/home/david/Desktop/fspdz/data"
 type_of_data: "audit"
 model_holders_ip: "127.0.0.1"
 model_holders_port: "6001"
 path_to_private_data: "/home/david/Desktop/spdz/Player-Data/Input-P2-0"
 path_to_this_repo: "/home/david/Desktop/fspdz"
 path_to_top_of_mpspdz: "/home/david/Desktop/spdz"
 compile: "false"
 model_type: "lr"
 metrics: "1,2,3"
 num_of_parties: "3"
 party: "1"
 compiler: "-R 64 -Y run"
 VM: "semi2k-party.x -N 3 -p 2 run"
 online: "false"