---
 path_to_public_data: "/home/sikhapentyala/FairSPDZ/data/fold0"
 party: "1"
 party_id_of_model_holder: "0"
 type_of_data: "audit"
 model_holders_ip: "10.128.0.4"
 model_holders_port: "6001"
 path_to_private_data: "/home/sikhapentyala/MP-SPDZ/Player-Data/Input-P1-0"
 path_to_this_repo: "/home/sikhapentyala/FairSPDZ"
 path_to_top_of_mpspdz: "/home/sikhapentyala/MP-SPDZ"
 compile: "true"
 model_type: "lr"
 metrics: "[demographic_parity,equal_opportunity]"
 recipients: "[0,1]"
 num_of_parties: "2"
 compiler: "-R 64 -Y run"
 VM: "semi2k-party.x -N 2 -p 0 run"
 protected_col: "45"
 protected_col_vals: "[0,1]"
 online: "true"
 my_private_ip: "10.128.0.5"