---
 path_to_public_data: "/home/david/Desktop/fspdz/data/fold0/lr_model.sav"
 party: "0"
 party_id_of_model_holder: "0"
 type_of_data: "model"
 model_holders_ip: "127.0.0.1"
 model_holders_port: "6001"
 path_to_private_data: "/home/david/Desktop/spdz/Player-Data/Input-P0-0"
 path_to_this_repo: "/home/david/Desktop/fspdz"
 path_to_top_of_mpspdz: "/home/david/Desktop/spdz"
 compile: "false"
 model_type: "lr"
 metrics: "[baseline,equalized_odds,demographic_parity,equal_opportunity]"
 recipients: "[0,1]"
 num_of_parties: "2"
 compiler: "-R 64 -Y run"
 VM: "semi2k-party.x -N 2 -p 0 run"
 protected_col: "45"
 protected_col_vals: "[0,1]"
 online: "false"
 my_private_ip: "127.0.0.1"